name: Package and Deploy Chrome Extension

on:
  push:
    branches:
    - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Read Version Number
        id: read_version
        run: echo "::set-output name=VERSION::$(cat audit-extension-version.txt)"

      - id: packExtensionDir
        uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
        with:
          extensionDir: 'src'
          zipFilePath: 'build/extension.zip'

      - uses: cardinalby/webext-buildtools-chrome-crx-action@v2
        with:
          zipFilePath: 'build/extension.zip'
          crxFilePath: 'griffin-audit-extension_v${{ steps.read_version.outputs.VERSION }}.crx'
          privateKey: ${{ secrets.AUDIT_EXTENSION_PRIVATE_KEY }}
          updateXmlPath: "updates.xml"
          updateXmlCodebaseUrl: "https://dev-extensions.griffin-web.com:7443/griffin-audit-extension.crx"

      - name: Copy file for latest version
        run: cp griffin-audit-extension_v${{ steps.read_version.outputs.VERSION }}.crx griffin-audit-extension_latest.crx

      - name: Upload to S3 with version
        run: |
            aws s3 cp griffin-audit-extension_v${{ steps.read_version.outputs.VERSION }}.crx s3://rhetorica-infrastructure-artifacts/ --region ap-southeast-2
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 

      - name: Upload to S3 as latest
        run: |
            aws s3 cp griffin-audit-extension_latest.crx s3://rhetorica-infrastructure-artifacts/ --region ap-southeast-2
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 

      - name: Upload updates to S3
        run: |
            aws s3 cp updates.xml s3://rhetorica-infrastructure-artifacts/updates-audit.xml --region ap-southeast-2
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 