name: Package and deploy Chrome Extension

on:
  push:
    branches:
    - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - id: packExtensionDir
      uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
      with:
        extensionDir: 'src'
        zipFilePath: 'build/extension.zip'
    - uses: cardinalby/webext-buildtools-chrome-crx-action@v2
      with:
        zipFilePath: 'build/extension.zip'
        crxFilePath: 'griffin-audit-extension.crx'
        privateKey: ${{ secrets.AUDIT_EXTENSION_PRIVATE_KEY }}
        updateXmlPath: "updates.xml"
        updateXmlCodebaseUrl: "https://object-storage.nz-por-1.catalystcloud.io/v1/AUTH_c8460d43eefd4292a57eb86db9ee8549/griffin-public/griffin-audit-extension.crx"
    - name: Upload CRX
      uses: iksaku/openstack-swift-action@master
      env:
        OS_AUTH_URL: ${{ secrets.AUTH_URL }}
        OS_PASSWORD: ${{ secrets.PASSWORD }}
        OS_PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
        OS_REGION_NAME: ${{ secrets.REGION_NAME }}
        OS_USERNAME: ${{ secrets.USERNAME }}
        OS_USER_DOMAIN_NAME: ${{ secrets.USER_DOMAIN_NAME }}
        OS_STORAGE_URL: ${{ secrets.STORAGE_URL }}
      with:
        args: upload griffin-public griffin-audit-extension.crx
    - name: Upload updates.xml
      uses: iksaku/openstack-swift-action@master
      env:
        OS_AUTH_URL: ${{ secrets.AUTH_URL }}
        OS_PASSWORD: ${{ secrets.PASSWORD }}
        OS_PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
        OS_REGION_NAME: ${{ secrets.REGION_NAME }}
        OS_USERNAME: ${{ secrets.USERNAME }}
        OS_USER_DOMAIN_NAME: ${{ secrets.USER_DOMAIN_NAME }}
        OS_STORAGE_URL: ${{ secrets.STORAGE_URL }}
      with:
        args: upload griffin-public updates.xml
